name: finance_hunter_app
description: "Finance Hunter application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  custom_fl_chart:
    path: packages/custom_fl_chart

  cupertino_icons: ^1.0.8
  go_router: ^15.1.3
  flutter_svg: ^2.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  fuzzy: ^0.5.1
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  drift: ^2.27.0
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.5
  path: ^1.9.1
  pretty_dio_logger: ^1.4.0
  flutter_dotenv: ^5.2.1
  worker_manager: ^7.2.6
  flutter_colorpicker: ^1.1.0
  flutter_secure_storage: ^9.2.4
  pin_code_fields: ^8.0.1
  local_auth: ^2.3.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  go_router_builder: ^3.0.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  drift_dev: ^2.27.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_gen:
  output: lib/ui_kit/gen/

flutter:
  generate: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launch_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_icon.png
  android: true
  ios: true
  fullscreen: true