name: finance_hunter_app
description: "Finance Hunter application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.3
  flutter_svg: ^2.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  go_router_builder: ^3.0.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6

flutter_gen:
  output: lib/ui_kit/gen/

  flutter_lints: ^6.0.0

flutter:
  generate: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

  uses-material-design: true

  assets:
    - assets/icons/
